FROM squidfunk/mkdocs-material:9

RUN pip install --no-cache-dir \
    mkdocs-git-revision-date-localized-plugin \
    mkdocs-glightbox \
    mkdocs-macros-plugin \
    mkdocs-include-markdown-plugin \
    mkdocs-awesome-pages-plugin \
    mike